---
title: "Client Report - Exploring Names"
subtitle: "Unit 1 Task 1"
author: "Sydney Ahlstrom Sanders"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute:
  kernel: python311
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pl.read_csv("https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv")
```

## QUESTION 1

__What was the earliest year that the name ‘Felisha’ was used?__

_The earliest year the name Felisha was used was in 1964._

```{python}
# Q1
felisha_year = (
    df.filter(pl.col("name") == "Felisha")
      .select(pl.col("year").min())
)
felisha_year

```


## QUESTION 2

__What year had the most babies named 'David'? How many babies were named 'David' that year?__

_In 1955 there were the most babies named David. 86389 babies were named David that year._

```{python}
# Q2
print(type(df))
print(pl.__version__)
david_peak = (
    df.filter(pl.col("name") == "David")
      .group_by("year")
      .agg(pl.col("Total").sum())
      .sort("Total", descending=True)
      .head(1)
)
david_peak

```


## QUESTION 3

__What year did your name hit its peak? How many babies were named your name in that year?__

_The use of my name, Sydney, peaked in the year 2000. 10297 babies were named Sydney that year, and I was one of the babies named that the next year!_

```{python}
# Q3
my_name = "Sydney"

sydney_peak = (
    df.filter(pl.col("name") == my_name)
      .group_by("year")
      .agg(pl.col("Total").sum())
      .sort("Total", descending=True)
      .head(1)
)
sydney_peak

```


## QUESTION 4

__In the most recent year, what was the most common female name in Utah?__ 

_I had a hard time figuring out how to sort names between male and female, so instead I just did the top 10 names in Utah in the most recent year. My best guess for which name is "female" is Olivia, but technically Oliver was the top name used._

```{python}
#Q4
latest_year = df.select(pl.col("year").max()).item()

utah_latest = (
    df.filter(pl.col("year") == latest_year)
      .sort("UT", descending=True)
      .head(10)
      .select(["name", "UT", "year"])
)
utah_latest

```


---
